
import { GoogleGenAI, Type, Modality } from "@google/genai";
import type { Preferences, Hairstyle } from "../types";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

function base64ToGenerativePart(base64: string, mimeType: string) {
  return {
    inlineData: {
      data: base64,
      mimeType,
    },
  };
}

export async function getHairstyleSuggestions(
  imageDataUrl: string,
  prefs: Preferences
): Promise<Hairstyle[]> {
  const [metadata, base64Data] = imageDataUrl.split(',');
  if (!base64Data) {
    throw new Error("Invalid image data URL");
  }

  const mimeType = metadata.match(/:(.*?);/)?.[1];
  if (!mimeType) {
    throw new Error("Could not determine MIME type from image data URL");
  }

  const imagePart = base64ToGenerativePart(base64Data, mimeType);
  const prompt = `
    Based on my preferences below and the attached photo of my face, please suggest 5 hairstyles.
    - Desired Length: ${prefs.length}
    - Desired Style: ${prefs.style}
    - Desired Vibe/Occasion: ${prefs.vibe}
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
            { text: prompt },
            imagePart
        ]
      },
      config: {
        systemInstruction: `You are an expert virtual hairstylist. Your role is to analyze a person's face from a photo and suggest 5 flattering hairstyles based on their facial features, face shape, and stated preferences. For each suggestion, provide a name for the hairstyle, a brief description, and a clear reason why it's a good match for the user.`,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            hairstyles: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  name: {
                    type: Type.STRING,
                    description: "The name of the hairstyle (e.g., 'Classic Bob', 'Textured Pixie Cut')."
                  },
                  description: {
                    type: Type.STRING,
                    description: "A short, appealing description of the hairstyle."
                  },
                  reason: {
                    type: Type.STRING,
                    description: "A concise explanation of why this hairstyle would suit the person in the photo, mentioning specific facial features if possible."
                  }
                },
                required: ["name", "description", "reason"]
              }
            }
          },
          required: ["hairstyles"]
        },
      },
    });

    const jsonText = response.text.trim();
    const result = JSON.parse(jsonText);
    
    if (!result.hairstyles || !Array.isArray(result.hairstyles)) {
        throw new Error("AI response did not contain valid hairstyle suggestions.");
    }

    return result.hairstyles;

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to get hairstyle suggestions from the AI. Please try again.");
  }
}


export async function generateHairstyleImage(
  imageDataUrl: string,
  hairstyle: Hairstyle
): Promise<string> {
  const [metadata, base64Data] = imageDataUrl.split(',');
  if (!base64Data) {
    throw new Error("Invalid image data URL for image generation");
  }

  const mimeType = metadata.match(/:(.*?);/)?.[1];
  if (!mimeType) {
    throw new Error("Could not determine MIME type from image data URL for image generation");
  }

  const imagePart = {
    inlineData: {
      data: base64Data,
      mimeType,
    },
  };

  const prompt = `Based on the provided image of a person, realistically edit their hairstyle to be a "${hairstyle.name}". 
  Hairstyle description: "${hairstyle.description}".
  Ensure the final image is high quality and that the person's face, expression, and the background remain unchanged. Only alter the hair.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt },
          imagePart,
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    const firstPart = response.candidates?.[0]?.content?.parts?.[0];
    if (firstPart && firstPart.inlineData) {
      const base64ImageBytes = firstPart.inlineData.data;
      const generatedMimeType = firstPart.inlineData.mimeType || 'image/png';
      return `data:${generatedMimeType};base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the AI.");
    }
  } catch (error) {
    console.error("Error calling Gemini Image API:", error);
    throw new Error(`Failed to generate image for hairstyle: ${hairstyle.name}.`);
  }
}
